syntax = "proto3";

package tamdb.proto.raft;

service RaftNodeService {
    rpc RequestVote(VoteRequest) returns (VoteResponse);
    rpc AppendEntries(AppendEntriesRequest) returns (AppendEntriesResponse);
}

message VoteRequest {
    uint64 term = 1;
    uint32 candidate_id = 2;
    uint64 last_log_index = 3;
    uint64 last_log_term = 4;
}

message VoteResponse {
    uint64 term = 1;
    bool vote = 2;
}

message LogEntry {
    uint64 term = 1;
    uint64 log_index = 2;
    repeated float input_vector = 3;
}

message AppendEntriesRequest {
    uint64 leader_term = 1;
    uint32 leader_id = 2;
    uint64 prev_log_index = 3;
    uint64 prev_log_term = 4;
    uint64 leader_commit_index = 5;
    repeated LogEntry logs = 6;
}

message AppendEntriesResponse {
    uint64 term = 1; 
    bool success = 2;
}

